# Generated by Django 3.1.7 on 2021-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('city', models.IntegerField(blank=True, db_column='City', null=True)),
                ('district', models.IntegerField(blank=True, db_column='District', null=True)),
                ('town', models.IntegerField(blank=True, db_column='Town', null=True)),
                ('description', models.IntegerField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phonenumber', models.IntegerField(blank=True, db_column='PhoneNumber', null=True)),
                ('email', models.IntegerField(blank=True, db_column='Email', null=True)),
                ('dob', models.IntegerField(blank=True, db_column='Dob', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.IntegerField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.IntegerField(blank=True, db_column='LastName', null=True)),
                ('midname', models.IntegerField(blank=True, db_column='MidName', null=True)),
            ],
            options={
                'db_table': 'fullname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, db_column='Name', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('discount', models.IntegerField(blank=True, db_column='Discount', null=True)),
                ('priceshipping', models.IntegerField(blank=True, db_column='PriceShipping', null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
